name: Running CI for hotel search
on:
  pull_request:
    branches:
      - main

jobs:
  run-integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: stable
      - name: Get flutter packages
        run: flutter pub get
      - name: Start Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          profile: pixel_3a
          avd-name: test-emulator
          disable-animations: true
          script: echo "Emulator started"
      - name: Run integration tests
        run: flutter test integration_test -d emulator-5554
