name: Running CI for hotel search
on:
  pull_request:
    branches:
      - main

jobs:
  run-integration-tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
      - name: Get flutter packages
        run: flutter pub get
      - name: Build iOS app
        run: flutter build ios --debug --no-codesign
      - uses: futureware-tech/simulator-action@v1
        with:
          model: "iPhone 13"
      - run: flutter test integration_test/house_integration_test.dart
